//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAPI.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class ContactInfo
    {
        public int ContactId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "FirstName is required")]
        public string FirstName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "LastName is required")]
        public string LastName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is required"), EmailAddress(ErrorMessage = "Enter valid EmailID")]
        public string Email { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Phone no. is required")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid phone Number.")]
        public string Phone { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Status is required")]
        public string Status { get; set; }
    }
}
